let vinhos = [
{
    nome: 'Vinho do Porto',
    tipo: ['Doce', 'Fortificado'],
    uva: ['Touriga Nacional', 'Tinta Barroca', 'Tinta Roriz'],
    regiao: 'Vale do Douro',
    historia: 'Com origem no século XVII...',
    melhorManeiraDegustar: '16°C a 18°C, como digestivo',
    acompanhamentos: "Queijos azuis', 'Nozes', 'Sobremesas à base de chocolate",
    notasDeDegustacao: 'Aroma de frutas secas e especiarias, sabor doce e intenso...',
    produtor: 'Taylors',
    ano: '2015',
    precoMedio: 'R$ 250,00 a R$ 500,00',

  },

  {
    nome: 'Chardonnay de Borgonha',
    tipo: ['Branco'],
    uva: ['Chardonnay'],
    regiao: 'Borgonha, França',
    historia: 'Um dos vinhos brancos mais prestigiados do mundo, o Chardonnay de Borgonha apresenta uma grande variedade de estilos, desde os mais leves e frutados até os complexos e encorpados.',
    melhorManeiraDegustar: 'Temperatura entre 10°C e 12°C, com frutos do mar, aves e queijos.',
    acompanhamentos: "Ostras', 'Camarão grelhado', 'Queijo Brie",
    notasDeDegustacao: 'Aroma de frutas brancas, manteiga, brioche e nuances minerais.',
    produtor: 'Domaine Leflaive',
    ano: '2018',
    precoMedio: 'R$ 500,00 a R$ 1.500,00',
 
  },
  {
    nome: 'Cabernet Sauvignon de Napa Valley',
    tipo: ['Tinto'],
    uva: ['Cabernet Sauvignon'],
    regiao: 'Napa Valley, Califórnia, EUA',
    historia: 'Um dos vinhos tintos mais famosos do mundo, o Cabernet Sauvignon de Napa Valley é conhecido por sua potência, taninos robustos e aromas de frutas negras e especiarias.',
    melhorManeiraDegustar: 'Temperatura ambiente, com carnes vermelhas grelhadas, churrasco e queijos duros.',
    acompanhamentos: "Bife de chorizo, cordeiro assado, queijo Parmesão",
    notasDeDegustacao: 'Aroma de amoras, cerejas, tabaco e especiarias, taninos macios e final longo.',
    produtor: 'Robert Mondavi',
    ano: '2017',
    precoMedio: 'R$ 300,00 a R$ 800,00',

  },
  {
    nome: 'Syrah do Rhône',
    tipo: ['Tinto'],
    uva: ['Syrah'],
    regiao: 'Vale do Rhône, França',
    historia: 'A Syrah é uma uva versátil que produz vinhos com aromas intensos de frutas negras, especiarias e notas florais.',
    melhorManeiraDegustar: 'Temperatura ambiente, com carnes vermelhas assadas, cordeiro e queijos semi-duros.',
    acompanhamentos: "Coelho à caçadora, ragu de carneiro, queijo Gruyère",
    notasDegustacao: 'Aroma de amoras, pimenta preta, violetas e especiarias, taninos firmes e final persistente.',
    produtor: 'M. Chapoutier',
    ano: '2016',
    precoMedio: 'R$ 250,00 a R$ 700,00',
 
  },
  {
    nome: 'Pinot Grigio do Trentino-Alto Adige',
    tipo: ['Branco'],
    uva: ['Pinot Grigio'],
    regiao: 'Trentino-Alto Adige, Itália',
    historia: 'Originário da França, o Pinot Grigio encontrou no norte da Itália um terroir ideal para expressar seus aromas frutados e mineralidade.',
    melhorManeiraDegustar: 'Bem gelado, como aperitivo ou acompanhado de pratos leves e frutos do mar.',
    acompanhamentos: "Salmão grelhado, risoto de aspargos, sushi",
    notasDeDegustacao: 'Aroma de pêra, maçã verde e flores brancas, sabor fresco e mineral.',
    produtor: 'Santa Margherita',
    ano: '2021',
    precoMedio: 'R$ 150,00 a R$ 300,00',
  },
  {
    nome: 'Riesling da Alsácia',
    tipo: ['Branco'],
    uva: ['Riesling'],
    regiao: 'Alsácia, França',
    historia: 'A Alsácia produz Rieslings de alta qualidade, com aromas complexos e boa acidez.',
    melhorManeiraDegustar: 'Bem gelado ou levemente resfriado, com pratos asiáticos, frutos do mar e queijos.',
    acompanhamentos: 'Pad Thai, sashimi, queijo Munster',
    notasDeDegustacao: 'Aroma de frutas brancas, petróleo, mel e minerais, sabor seco e equilibrado.',
    produtor: 'Trimbach',
    ano: '2020',
    precoMedio: 'R$ 200,00 a R$ 500,00',
  },
  {
    nome: 'Nebbiolo do Piemonte',
    tipo: ['Tinto'],
    uva: ['Nebbiolo'],
    regiao: 'Piemonte, Itália',
    historia: 'A Nebbiolo é a uva que dá origem a vinhos tintos elegantes e complexos, como o Barolo e o Barbaresco.',
    melhorManeiraDegustar: 'Temperatura ambiente, com carnes vermelhas assadas, trufas e queijos maturados.',
    acompanhamentos: 'Tagliata, risoto de trufas, queijo Grana Padano',
    notasDegustacao: 'Aroma de rosas, alcaçuz, tabaco e especiarias, taninos firmes e final longo.',
    produtor: 'Gaja',
    ano: '2015',
    precoMedio: 'R$ 1.000,00 a R$ 3.000,00',
  },
  {
    nome: 'Sauvignon Blanc de Sancerre',
    tipo: ['Branco'],
    uva: ['Sauvignon Blanc'],
    regiao: 'Sancerre, França',
    historia: 'Conhecido por sua mineralidade e aromas de frutas cítricas e ervas frescas, o Sauvignon Blanc de Sancerre é um clássico da França.',
    melhorManeiraDegustar: 'Bem gelado, com pratos leves, frutos do mar e queijos de cabra.',
    acompanhamentos: 'Ostras, camarão grelhado, queijo chèvre',
    notasDegustacao: 'Aroma de grama cortada, maracujá, limão e pêssego branco, sabor fresco e mineral.',
    produtor: 'Domaine Vacheron',
    ano: '2021',
    precoMedio: 'R$ 250,00 a R$ 600,00',
  },
  {
    nome: 'Tempranillo de Rioja',
    tipo: ['Tinto'],
    uva: ['Tempranillo'],
    regiao: 'Rioja, Espanha',
    historia: 'A Rioja é uma das regiões vinícolas mais famosas da Espanha, produzindo vinhos tintos com taninos elegantes e aromas de frutas vermelhas e especiarias.',
    melhorManeiraDegustar: 'Temperatura ambiente, com carnes vermelhas assadas, embutidos e queijos curados.',
    acompanhamentos: 'Churrasco, jamón ibérico, queijo Manchego',
    notasDegustacao: 'Aroma de cereja, amora, baunilha e tabaco, taninos macios e final persistente.',
    produtor: 'Lagar de Cerda',
    ano: '2018',
    precoMedio: 'R$ 200,00 a R$ 500,00',
  },
  {
    nome: 'Zinfandel da Califórnia',
    tipo: ['Tinto'],
    uva: ['Zinfandel'],
    regiao: 'Califórnia, EUA',
    historia: 'O Zinfandel é uma uva versátil que produz vinhos tintos com alta graduação alcoólica, aromas de frutas vermelhas e especiarias, e às vezes notas de frutas secas.',
    melhorManeiraDegustar: 'Levemente resfriado, com carnes grelhadas, pizzas e queijos azuis.',
    acompanhamentos: 'Costeletas de porco, pizza de pepperoni, queijo Gorgonzola',
    notasDegustacao: 'Aroma de morango, framboesa, pimenta preta e especiarias, paladar encorpado e frutado.',
    produtor: 'Ridge Vineyards',
    ano: '2019',
    precoMedio: 'R$ 250,00 a R$ 600,00',
  },
  {
    nome: 'Gewürztraminer da Alsácia',
    tipo: ['Branco'],
    uva: ['Gewürztraminer'],
    regiao: 'Alsácia, França',
    historia: 'Conhecido por seus aromas intensos de lichia, rosas e especiarias, o Gewürztraminer é um vinho branco doce ou semi-doce.',
    melhorManeiraDegustar: 'Levemente resfriado, como aperitivo ou acompanhado de queijos azuis, foie gras e sobremesas.',
    acompanhamentos: 'Queijo Roquefort, foie gras, tarte tatin',
    notasDegustacao: 'Aroma de lichia, rosa, cravo e especiarias, paladar doce e perfumado.',
    produtor: 'Domaine Schlumberger',
    ano: '2020',
    precoMedio: 'R$ 200,00 a R$ 400,00',
  },


];